// Generated by gencpp from file camera_detector/associationWouter.msg
// DO NOT EDIT!


#ifndef CAMERA_DETECTOR_MESSAGE_ASSOCIATIONWOUTER_H
#define CAMERA_DETECTOR_MESSAGE_ASSOCIATIONWOUTER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace camera_detector
{
template <class ContainerAllocator>
struct associationWouter_
{
  typedef associationWouter_<ContainerAllocator> Type;

  associationWouter_()
    : leftLegObjectID()
    , rightLegObjectID()
    , p(0.0)  {
    }
  associationWouter_(const ContainerAllocator& _alloc)
    : leftLegObjectID(_alloc)
    , rightLegObjectID(_alloc)
    , p(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _leftLegObjectID_type;
  _leftLegObjectID_type leftLegObjectID;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _rightLegObjectID_type;
  _rightLegObjectID_type rightLegObjectID;

   typedef float _p_type;
  _p_type p;





  typedef boost::shared_ptr< ::camera_detector::associationWouter_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera_detector::associationWouter_<ContainerAllocator> const> ConstPtr;

}; // struct associationWouter_

typedef ::camera_detector::associationWouter_<std::allocator<void> > associationWouter;

typedef boost::shared_ptr< ::camera_detector::associationWouter > associationWouterPtr;
typedef boost::shared_ptr< ::camera_detector::associationWouter const> associationWouterConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera_detector::associationWouter_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera_detector::associationWouter_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace camera_detector

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'camera_detector': ['/home/nvidia/detector_ws/src/camera_detector/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::camera_detector::associationWouter_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera_detector::associationWouter_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_detector::associationWouter_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_detector::associationWouter_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_detector::associationWouter_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_detector::associationWouter_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera_detector::associationWouter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "afaa1cc21178a79b474c1a60f52fd2e4";
  }

  static const char* value(const ::camera_detector::associationWouter_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xafaa1cc21178a79bULL;
  static const uint64_t static_value2 = 0x474c1a60f52fd2e4ULL;
};

template<class ContainerAllocator>
struct DataType< ::camera_detector::associationWouter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera_detector/associationWouter";
  }

  static const char* value(const ::camera_detector::associationWouter_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera_detector::associationWouter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string leftLegObjectID\n\
string rightLegObjectID\n\
float32 p\n\
";
  }

  static const char* value(const ::camera_detector::associationWouter_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera_detector::associationWouter_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.leftLegObjectID);
      stream.next(m.rightLegObjectID);
      stream.next(m.p);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct associationWouter_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera_detector::associationWouter_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::camera_detector::associationWouter_<ContainerAllocator>& v)
  {
    s << indent << "leftLegObjectID: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.leftLegObjectID);
    s << indent << "rightLegObjectID: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.rightLegObjectID);
    s << indent << "p: ";
    Printer<float>::stream(s, indent + "  ", v.p);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_DETECTOR_MESSAGE_ASSOCIATIONWOUTER_H
