// Generated by gencpp from file camera_detector/person.msg
// DO NOT EDIT!


#ifndef CAMERA_DETECTOR_MESSAGE_PERSON_H
#define CAMERA_DETECTOR_MESSAGE_PERSON_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <camera_detector/personAssociation.h>

namespace camera_detector
{
template <class ContainerAllocator>
struct person_
{
  typedef person_<ContainerAllocator> Type;

  person_()
    : p()
    , personID(0)  {
    }
  person_(const ContainerAllocator& _alloc)
    : p(_alloc)
    , personID(0)  {
  (void)_alloc;
    }



   typedef std::vector< ::camera_detector::personAssociation_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::camera_detector::personAssociation_<ContainerAllocator> >::other >  _p_type;
  _p_type p;

   typedef int32_t _personID_type;
  _personID_type personID;





  typedef boost::shared_ptr< ::camera_detector::person_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera_detector::person_<ContainerAllocator> const> ConstPtr;

}; // struct person_

typedef ::camera_detector::person_<std::allocator<void> > person;

typedef boost::shared_ptr< ::camera_detector::person > personPtr;
typedef boost::shared_ptr< ::camera_detector::person const> personConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera_detector::person_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera_detector::person_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace camera_detector

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'camera_detector': ['/home/nvidia/detector_ws/src/camera_detector/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::camera_detector::person_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera_detector::person_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_detector::person_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_detector::person_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_detector::person_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_detector::person_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera_detector::person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c8df5b68db3ef7d56cbf82afb064ee74";
  }

  static const char* value(const ::camera_detector::person_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc8df5b68db3ef7d5ULL;
  static const uint64_t static_value2 = 0x6cbf82afb064ee74ULL;
};

template<class ContainerAllocator>
struct DataType< ::camera_detector::person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera_detector/person";
  }

  static const char* value(const ::camera_detector::person_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera_detector::person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "personAssociation[] p\n\
int32 personID\n\
\n\
================================================================================\n\
MSG: camera_detector/personAssociation\n\
int32 leftLegObject\n\
string leftLegObjectID\n\
int32 rightLegObject\n\
string rightLegObjectID\n\
float32 associationProbability\n\
\n\
\n\
";
  }

  static const char* value(const ::camera_detector::person_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera_detector::person_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.p);
      stream.next(m.personID);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct person_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera_detector::person_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::camera_detector::person_<ContainerAllocator>& v)
  {
    s << indent << "p[]" << std::endl;
    for (size_t i = 0; i < v.p.size(); ++i)
    {
      s << indent << "  p[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::camera_detector::personAssociation_<ContainerAllocator> >::stream(s, indent + "    ", v.p[i]);
    }
    s << indent << "personID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.personID);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_DETECTOR_MESSAGE_PERSON_H
