// Generated by gencpp from file camera_detector/personAssociation.msg
// DO NOT EDIT!


#ifndef CAMERA_DETECTOR_MESSAGE_PERSONASSOCIATION_H
#define CAMERA_DETECTOR_MESSAGE_PERSONASSOCIATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace camera_detector
{
template <class ContainerAllocator>
struct personAssociation_
{
  typedef personAssociation_<ContainerAllocator> Type;

  personAssociation_()
    : leftLegObject(0)
    , leftLegObjectID()
    , rightLegObject(0)
    , rightLegObjectID()
    , associationProbability(0.0)  {
    }
  personAssociation_(const ContainerAllocator& _alloc)
    : leftLegObject(0)
    , leftLegObjectID(_alloc)
    , rightLegObject(0)
    , rightLegObjectID(_alloc)
    , associationProbability(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _leftLegObject_type;
  _leftLegObject_type leftLegObject;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _leftLegObjectID_type;
  _leftLegObjectID_type leftLegObjectID;

   typedef int32_t _rightLegObject_type;
  _rightLegObject_type rightLegObject;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _rightLegObjectID_type;
  _rightLegObjectID_type rightLegObjectID;

   typedef float _associationProbability_type;
  _associationProbability_type associationProbability;





  typedef boost::shared_ptr< ::camera_detector::personAssociation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera_detector::personAssociation_<ContainerAllocator> const> ConstPtr;

}; // struct personAssociation_

typedef ::camera_detector::personAssociation_<std::allocator<void> > personAssociation;

typedef boost::shared_ptr< ::camera_detector::personAssociation > personAssociationPtr;
typedef boost::shared_ptr< ::camera_detector::personAssociation const> personAssociationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera_detector::personAssociation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera_detector::personAssociation_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace camera_detector

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'camera_detector': ['/home/nvidia/detector_ws/src/camera_detector/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::camera_detector::personAssociation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera_detector::personAssociation_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_detector::personAssociation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_detector::personAssociation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_detector::personAssociation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_detector::personAssociation_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera_detector::personAssociation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ed69e3f8f8a35b73079f660bd12324d6";
  }

  static const char* value(const ::camera_detector::personAssociation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xed69e3f8f8a35b73ULL;
  static const uint64_t static_value2 = 0x079f660bd12324d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::camera_detector::personAssociation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera_detector/personAssociation";
  }

  static const char* value(const ::camera_detector::personAssociation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera_detector::personAssociation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 leftLegObject\n\
string leftLegObjectID\n\
int32 rightLegObject\n\
string rightLegObjectID\n\
float32 associationProbability\n\
\n\
\n\
";
  }

  static const char* value(const ::camera_detector::personAssociation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera_detector::personAssociation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.leftLegObject);
      stream.next(m.leftLegObjectID);
      stream.next(m.rightLegObject);
      stream.next(m.rightLegObjectID);
      stream.next(m.associationProbability);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct personAssociation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera_detector::personAssociation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::camera_detector::personAssociation_<ContainerAllocator>& v)
  {
    s << indent << "leftLegObject: ";
    Printer<int32_t>::stream(s, indent + "  ", v.leftLegObject);
    s << indent << "leftLegObjectID: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.leftLegObjectID);
    s << indent << "rightLegObject: ";
    Printer<int32_t>::stream(s, indent + "  ", v.rightLegObject);
    s << indent << "rightLegObjectID: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.rightLegObjectID);
    s << indent << "associationProbability: ";
    Printer<float>::stream(s, indent + "  ", v.associationProbability);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_DETECTOR_MESSAGE_PERSONASSOCIATION_H
